spring:
  flyway:
    locations: classpath:db/migration
  datasource:
    url: jdbc:mysql://localhost/demo
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true